### ISSUE TITLE
Custom events?

### ISSUE THREAD

**Issue by zhoul-HS** [trello/navi#27]
I initially thought this is meant to solve the current state of using callbacks and saving listener references in e.g. `onAttach`, but it seems that there are only built-in events (mostly lifecycle).
Why not giving the ability to create and listen to arbitrary events that are relevant for our app? especially since there's already logic to handle unsupported events!

**Comment by dlew** [comment]
I've given this a lot of thought over the months. The issue with allowing custom events is that the library then becomes so generic that it's somewhat meaningless.

Plus, what time do you really save then? For custom events, you have to:

1. Write your own `Event`.
2. Write a custom `Activity`/`Fragment` that emits those events.

...Which is basically 90% of the library already.

**Comment by zhoul-HS** [comment]
I agree with the fact it doesn't save much time, but sealing it makes it impossible to use navi and callbacks "the same way" - meaning I have different structure for handling lifecycle events and different structure for handling custom events. With the ability to add custom events, users can have a unified have to handling communication between components.

I mean if i'm already using callbacks, i'll use it all the way :)

**Comment by dlew** [comment]
I've pondered this more over the last week. I still think custom events are outside the scope for now.

There is essentially one use case for Navi: building reusable components for libraries. If that component is in a library, then custom events are pointless (since then you push a lot of responsibility onto the consumer of the library).

Also, allowing custom events means you have to completely reimplement the `NaviEmitter`, since you have to make sure that everyone is using the same set of listeners. There's no way to currently "add on" events to an existing listenable object, nor do I think it'd make sense to add an API for it when it won't often be used.

**Comment by lujop** [comment]
I understand your point @dlew but I think that will be very useful to be able to manage some Google Play services lifecycle: GoogleApiClient connected, Google SignIn credentials ready,...

If you use that libraries and want to make components that need apiClient or credentials will be very useful to include that in events.

How you do manage that? In some components on top of Navi or an unrelated way?
