### ISSUE TITLE
remove enum Event.Type and improve the ALL listener

### ISSUE THREAD

**Issue by passsy** [trello/navi#30]
The `Event.Type` `enum` is basically never used and could be removed to reduce complexity.

It's only used when emitting events for the `ALL` listener where `Event.Type` is used as parameter to distinguish between events. But this parameter makes no sense to me. `Event.Type#CREATE` will be emitted twice when `NaviActivity#onCreate(Bundle, PersistableBundle)` is called because the events `CREATE_PERSISTABLE` and `CREATE` have the same type (`== Event.Type#CREATE`).

When listening to `ALL` I would expect to receive all `Events` emitted (`Event<T>` not `Event.Type`) and the data. This requires a new listener with two parameters matching `NaviEmitter#emitEvent(Event<T> event, T data)`.

**Comment by passsy** [comment]
reference: https://github.com/trello/navi/pull/20

**Comment by dlew** [comment]
I'll have to think on this. Without `Event.Type` you can't distinguish between, for example, `Event.CREATE` and `Event.SAVE_INSTANCE_STATE` without reference equality. Maybe that's alright since we currently control all instances of `Event`, but it seems less flexible for future modification.

The fact that `CREATE` is emitted twice has more to do with the `Activity` lifecycle than the existence of `Event.Type`. That should probably go into its own issue to solve.

**Comment by dlew** [comment]
I'm going to close this in favor of solving #33. Once that's done we can see if `ALL` is slightly more useful.
