### ISSUE TITLE
Use of raw types masks potential Listener contract failure

### ISSUE THREAD

**Issue by tbsandee** [trello/navi#68]
If you check out this repo: https://github.com/tbsandee/navi/ you can see a commit that cleans up a use of raw type `Event` in `NaviComponent` and related. Once I dug in and followed that rabbit hole down, I found some errors that these uses of raw types were masking. Specifically, non `T` types were being passed into parameterized `Listener<T>` objects in the underlying implementation. It's not a big deal and the code functions, but it might be a good idea to clean it up -- maybe in the rxjava2 rearch.

This branch doesn't compile -- it has errors where the issues are to illustrate them.

**Comment by dlew** [comment]
Having done some research, it looks like the correct answer is actually to change `Listener.call(T)` -> `Listener.call(Object)`. It needs to accept any `Object` (which is why you're using the wildcard) but using `Listener<?>` requires that the `call()` is done on the right capture type, which can't be guaranteed at compile time.

A relevant article (about stuff in the Java API itself that does this): http://smallwig.blogspot.dk/2007/12/why-does-setcontains-take-object-not-e.html

The downside to doing it correctly is that everyone would need to start using explicit casting for the return type of `Listener`, which would be a huge PITA when we're supposed to be doing handling this internally. Maybe we could create some wrapper type for `Listener` which does generics correctly, then we can explicitly cast it ourselves...

I'll have to think on this more.

**Comment by dlew** [comment]
I've decided that the internals of this library can remain somewhat ugly for the sake of the public API.
