### ISSUE TITLE
NullpointerException with component

### ISSUE THREAD

**Issue by vanniktech** [trello/navi#95]
I'm getting two NPE's regarding the component in NaviOnSubscribe. The first one is a NPE on https://github.com/trello/navi/blob/e2882196b97f58cd251f5ff14b07c1ab60816884/navi/src/main/java/com/trello/navi2/rx/NaviOnSubscribe.java#L40 and the second one is https://github.com/trello/navi/blob/e2882196b97f58cd251f5ff14b07c1ab60816884/navi/src/main/java/com/trello/navi2/rx/NaviOnSubscribe.java#L56

Both crashes I'm only getting for one user with a Moto G (5S) Plus (Android 7)

I can't think of any way how to reproduce this or what's the underlying problem for it. I know for sure that `NaviComponent` that I pass in the constructor is not null as it's the Activity that I'm passing.

**Comment by dlew** [comment]
The code leading up to there is pretty simple, so to me there are only two possibilities:

- `component` is null (since that's the only object that could NPE on those lines).
- The crash reports are wrong in some way (unlikely to me, but I can't think of anything else!)

I'm pretty baffled as well. Maybe it's worth adding an null-check in the constructor, so we crash if you even try to use a null variable? Just to rule out that it can't possibly be the constructor?

**Comment by vanniktech** [comment]
Adding the null check seems like a good idea. It has happened both times 2 and then never again until now.
